export const storeProducts=[
  {id:1,
    title:"Air Jordan",
    img:"https://i0.wp.com/www.zapatillasbaratasspain.com/wp-content/uploads/2020/05/06071e75.jpg?fit=1620%2C1620&ssl=1",
    price:50,
    company:"Nike",
    info:"Air Jordan 1 Retro High OG 'Black Toe' 555088-125",
    inCart:false,
    count:0,
    total:0
  },
  {id:2,
    title:"Adizero Boston 10",
    img: "https://static.runnea.com/images/202207/adidas-adizero-adios7-zapatillas-chaussure-scarpe-400x400x80xX.jpg?1",
    price:80,
    company:"Adidas",
    info:"Running",
    inCart:false,
    count:0,
    total:0
  },
  {id:3,
    title:"Running Foam Tempo",
    img: "https://www.runnea.com/archivos/201504/new-balance-1080v5-p-300x300x80xX.jpg",
    price:63,
    company:"New Balance",
    info:"Fresh Foam midsole cushioning is precision-engineered to deliver a lightweight ride and superior cushioning",
    inCart:false,
    count:0,
    total:0
  },
  {id:4,
    title:"Puma RS-X3",
    img: "https://www.moov.com.ar/on/demandware.static/-/Sites-dabra-catalog/default/dw4144eb30/products/PU_373308-01/PU_373308-01-1.JPG",
    price:40,
    company:"Puma",
    info: " Unisex, Textil. Nylon, Rubber sole and lace-up closure",
    inCart:false,
    count:0,
    total:0
  },
  {id:5,
    title:"Sport Woman Topper",
    img: "https://pacogarcia.vteximg.com.br/arquivos/ids/174746-450-450/25591-1.jpg",
    price: 55,
    company: "Topper",
    info: "It is a model designed for demanding runners who prioritize support and low weight, without sacrificing speed. Its upper is made of open mesh, includes film appliqués and an openwork plastic side piece to increase protection and minimize weight.",
    inCart:false,
    count:0,
    total:0
  },
  {id:6,
    title:"Nike Air Max 270",
    img: "https://www.dexter.com.ar/on/demandware.static/-/Sites-dabra-catalog/default/dw1a079279/products/NI_AT6174-300/NI_AT6174-300-1.JPG",
    price: 70,
    company: "Nike",
    info: "The Nike Air Max 270 is a new silhouette that combines the best of the Air Max 180 and Air Max 93. It features a large Max Air unit in the heel and a large Air unit in the forefoot for a comfortable ride. The upper is made of mesh and synthetic materials, and the outsole is made of rubber.",
    inCart:false,
    count:0,
    total:0
  },
  {id:7,
    title:"Reebock Royal Glide",
    img:"https://assets.reebok.com/images/w_600,h_600,f_auto,q_auto:sensitive,fl_lossy/8d845e9850444a0a9acaa8cd00763665_9366/Reebok_Royal_Ultra_Green_CN4567_01_standard.jpg",
    price: 90,
    company: "Reebock",
    info: "The Reebok Royal Glide is a model designed for demanding runners who prioritize support and low weight, without sacrificing speed. Its upper is made of open mesh, includes film appliqués and an openwork plastic side piece to increase protection and minimize weight.",
    inCart:false,
    count:0,
    total:0
  },
  {id:8,
    title:"Reebock One Cushion 3.0",
    img: "https://static.runnea.com/images/201411/reebok-one-cushion-2-400x400x80xX.jpg?1",
    price: 60,
    company: "Reebock",
    info: "The Reebok One Cushion 3.0 is a model designed for demanding runners who prioritize support and low weight, without sacrificing speed. Its upper is made of open mesh, includes film appliqués and an openwork plastic side piece to increase protection and minimize weight.",
    inCart:false,
    count:0,
    total:0
  }
]

export const detailProduct={
    id:1,
    title:"Air Jordan",
    img:"https://i0.wp.com/www.zapatillasbaratasspain.com/wp-content/uploads/2020/05/06071e75.jpg?fit=1620%2C1620&ssl=1",
    price:50,
    company:"Nike",
    info:"Air Jordan 1 Retro High OG 'Black Toe' 555088-125",
    inCart:false,
    count:0,
    total:0
  };
  